name: Xzonn 的小站
description: 祈福京都动画，愿逝者安息，生者坚强。
url: https://xzonn.github.io
author: Xzonn
markdown: kramdown
permalink: /:title/
version: v2.0
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-feed
exclude:
  - LICENSE
paginate: 10
paginate_path: /page/:num/