name: Xzonn 的小站
description: 这是 Xzonn 的小站。
url: 
markdown: kramdown
permalink: /:title/
version: v2.0
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
exclude:
    - LICENSE
    - README.md
paginate: 10
paginate_path: /page/:num/