author: Xzonn
description: 2020年新年快乐！
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
exclude:
  - .git
  - _drafts/Debug
  - Debug
  - LICENSE
markdown: kramdown
name: Xzonn 的小站
permalink: /posts/:title.html
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
timezone: Asia/Shanghai
url: https://xzonn.github.io
server: https://xzonn.top
version: v3.0