algolia:
  application_id: "ZVIOW9GL6U"
  index_name: "xzonn_top"
  files_to_exclude:
    - index.html
    - index.md
    - posts.html
    - search.html
  nodes_to_index: "figcaption,p,li"
  settings:
    searchableAttributes:
      - title
      - headings
      - unordered(tags)
      - unordered(content)
    attributesToHighlight:
      - content
      - headings
      - tags
      - title
author: Xzonn
defaults:
  - values:
      layout: "default"
      license: "by-nc-sa"
      head_image_width: 1280
      head_image_height: 720
      head_image_shown: true
  - scope:
      type: "posts"
    values:
      permalink: /posts/:title.html
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - jsconfig.json
  - package.json
  - package-lock.json
  - "*.less"
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
name: Xzonn的小站
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter
timezone: Asia/Shanghai
theme: 
repository: Xzonn/xzonn.github.io
url: https://xzonn.top
image_cdn: https://images.xzonn.top/github
static_cdn: https://cdn.jsdelivr.net/gh/Xzonn/xzonn.github.io@master
version: v5.0
sass:
  sass_dir: assets/css
  load_paths: 
    - assets/css
    - node_modules
  sourcemap: always
  style: compressed