name: Xzonn 的小站
description: 2020年新年快乐！
url: https://xzonn.github.io
author: Xzonn
markdown: kramdown
permalink: /:title/
version: v2.0
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-feed
exclude:
  - LICENSE
timezone: Asia/Shanghai