author: Xzonn
description: 2020年新年快乐！
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
exclude:
  - LICENSE
markdown: kramdown
name: Xzonn 的小站
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
timezone: Asia/Shanghai
url: https://xzonn.github.io
version: v2.0