author: Xzonn
description: 2020年新年快乐！
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
exclude:
  - .git
  - _drafts/Debug
  - Debug
  - LICENSE
markdown: kramdown
name: Xzonn 的小站
permalink: /posts/:title.html
plugins:
  - jekyll-feed
  - jekyll-sitemap
timezone: Asia/Shanghai
url: https://xzonn.top
cdnpath: https://cdn.jsdelivr.net/gh/Xzonn/xzonn.github.io@master
version: v3.0