algolia:
  application_id: "TN8HK9FU3W"
  index_name: "xzonn_top"
  files_to_exclude:
    - index.html
    - index.md
    - pages/**/index.*
  nodes_to_index: "p,h2,h3"
  settings:
    searchableAttributes:
      - title
      - headings
      - unordered(tags)
      - unordered(content)
    attributesToHighlight:
      - content
      - headings
      - tags
      - title
author: Xzonn
defaults:
  - values:
      base_css: "base"
      layout: "default"
      license: "by-nc-sa"
      head_image_width: 1280
      head_image_height: 720
      head_image_shown: true
  - scope:
      type: "posts"
    values:
      permalink: /posts/:title.html
  - scope:
      type: "study"
    values:
      layout: study
      permalink: /posts/:title.html
  - scope:
      type: "interviews"
    values:
      base_css: "interviews.base"
      css: "interviews"
collections:
  interviews:
    output: true
  study:
    output: true
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - jsconfig.json
  - package.json
  - package-lock.json
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
name: Xzonn的小站
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter
timezone: Asia/Shanghai
url: https://xzonn.top
image_cdn: https://images.xzonn.top/github
static_cdn: https://cdn.jsdelivr.net/gh/Xzonn/xzonn.github.io@master
version: v4.0
sass:
  load_paths:
    - css
  sourcemap: always
  style: compressed